angular.module("vendorportal-vf-service", [
 'vf-cache-vfCommon'
 'vf-cache-order'
 'vf-cache-item'
 'vf-cache-apiSetting'
 'vf-cache-shipNotice'
 'vf-cache-invoice'
 'vf-cache-batch'
 'vf-cache-self-testing'
 'vf-cache-item-creation'
 'vf-api-order'
 'vf-api-item'
 'vf-api-invoice'
 'vf-api-shipnotice'
 'vf-api-orderException'
 'vf-api-orderAck'
 'vf-api-address'
 'vf-api-batch'
 'vf-api-self-testing'
 'vf-api-orderStatus'
 'vf-api-manufacturer'
 'vf-api-item-creation'
 'vf-api-product-roadmap'
 'vf-api-batch-item-creation'
 'vf-api-item-update'
 'vf-api-item-profile'
])

