variables:

before_script:
  # output environment variables (usefull for debugging, propably not what you want to do if your ci server is public)
  - env

stages:
  - test

unit-test:
  stage: test
  script:
  # Auto generate image version by Gitlab build id
  #- 'export image_ver=$image_main_ver.$CI_BUILD_ID'
  #- 'echo Image Version is : $image_ver'
  - 'mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -Pcoverage-per-test'
  - 'mvn sonar:sonar'
