import { OnInit, ElementRef } from '@angular/core';
import { ComponentBase } from './../ComponentBase';
export declare const DROP_LIST_VALUE_ACCESSOR: any;
export declare class DropListComponent extends ComponentBase implements OnInit {
    private elementRef;
    onChange: any;
    onTouched: any;
    private innerDataSource;
    private $el;
    private innerValue;
    private dataSource;
    private inputFocused;
    private filterChanged;
    private focusedIndex;
    private pages;
    private pageIndex;
    private pageCount;
    private totalCount;
    private _pageSize;
    private filterKey;
    private pageSize;
    private pageChanged;
    constructor(elementRef: ElementRef);
    ngOnInit(): void;
    ngOnChanges(changesObj: any): void;
    private pageClick(event, p);
    writeValue(value: any): void;
    registerOnChange(fn: (_: any) => {}): void;
    registerOnTouched(fn: () => {}): void;
    private emitValue();
    private dataChange(p);
    private inputKeyDown(event);
    private inputFocus();
    private inputBlur(event);
    private setFocusIndex(index);
    private itemMouseDown(event);
    private itemSelect(item);
    private buildPages();
    private calcPageInfo();
}
