import { NegAjax } from './negAjax';
import { NegAlert } from './negAlert';
import { NegAuth } from './negAuth';
import { NegBizLog } from './negBizLog';
import { NegBreadcrumb } from './negBreadcrumb';
import { NegConfigService } from './negConfigService';
import { NegDfisUploader } from './negDfisUploader';
import { NegEventBus } from './negEventBus';
import { NegGlobalConfig } from './negGlobalConfig';
import { NegGlobalLoading } from './negGlobalLoading';
import { NegStorage } from './negStorage';
import { NegTranslate } from './negTranslate';
import { NegUserProfile } from './negUserProfile';
import { NegValidators } from './negValidators';
import { NegUtil } from './negUtil';
import { NegFeedback } from './negFeedback';
import { NegMessageBox } from './negMessageBox';
import { NegMultiTab } from './negMultiTab';
import { TranslateService, TranslateLoader } from '@ngx-translate/core';
export { TranslateService, TranslateLoader, NegAjax, NegAlert, NegAuth, NegBizLog, NegBreadcrumb, NegConfigService, NegDfisUploader, NegEventBus, NegGlobalConfig, NegGlobalLoading, NegStorage, NegTranslate, NegUserProfile, NegValidators, NegUtil, NegFeedback, NegMessageBox, NegMultiTab };
export declare const CORE_SERVICES: (typeof NegUtil | typeof TranslateService | typeof NegTranslate | typeof NegMessageBox | typeof NegAlert | typeof NegGlobalLoading | typeof NegAjax | typeof NegStorage | typeof NegAuth | typeof NegBizLog | typeof NegEventBus | typeof NegBreadcrumb | typeof NegConfigService | typeof NegDfisUploader | typeof NegGlobalConfig | typeof NegUserProfile | typeof NegValidators | typeof NegFeedback | typeof NegMultiTab)[];
