angular.module("vendorportal-service", [
 'vp-cache-printer'
 'vp-api-trace'
 'vp-api-user'
 'vp-api-vendorContact'
 'vp-api-contract'
 'vp-api-warehouse'
 'vp-api-configuration'
 'vp-api-role'
 'vp-api-vendormgr'
 'vp-api-rolePermission'
 'vp-api-vendorUser'
 'vp-api-dashboard'
 'vp-api-userFeedback'
 'vp-api-registration'
 'vp-api-application-form'
 'vp-api-stocking-po'
 'vp-cache-auth'
 'vp-cache-registration'
 'vp-cache-monitor'
 'vp-api-management'
 'vp-api-captcha'
 'vp-api-latest-update'
 'vp-api-vendor-draft'
 'vp-api-eims'
 'vp-api-territory'
])

